/*
-- Query: SELECT g.name AS genre, s.release_year, COUNT(*) AS total
FROM show_genres sg
JOIN genres g ON sg.genre_id = g.id
JOIN shows s ON sg.show_id = s.id
GROUP BY g.name, s.release_year
ORDER BY s.release_year, total DESC
LIMIT 0, 1000

-- Date: 2025-08-14 22:48
*/
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,1925,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1942,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1942,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1943,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1943,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1944,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1944,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1945,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1945,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,1945,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1946,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1946,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,1946,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1947,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1947,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1954,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1954,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1954,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1954,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1954,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1955,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1955,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1955,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1955,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1956,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1956,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1956,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1956,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1956,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1958,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1958,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1958,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1958,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1958,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1959,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1959,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1960,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1960,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1960,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1960,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1960,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1960,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1961,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1961,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1962,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1962,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1962,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1962,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1962,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1962,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1963,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,1963,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1963,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1963,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,1963,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1964,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1964,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1964,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1964,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1965,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1965,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1965,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1966,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1966,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1966,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1967,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1967,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1967,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,1967,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1967,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1967,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1967,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1968,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1968,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1968,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1968,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1968,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1968,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1968,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1969,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1969,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1969,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1969,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1970,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1970,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1970,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1970,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1970,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1971,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1971,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1971,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1971,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1971,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1971,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1971,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1971,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1972,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1972,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1972,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1972,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1972,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1972,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,1972,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1972,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1972,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1973,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1973,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1973,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1973,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1973,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1973,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1973,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1973,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1973,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1973,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1974,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1974,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1974,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1974,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1974,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1974,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1975,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1975,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1975,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1975,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1975,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1975,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1976,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1976,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1976,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1976,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1976,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1976,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1976,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1976,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1976,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1977,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1977,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1977,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1977,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1977,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1978,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1978,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1978,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1978,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1979,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1979,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1979,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1979,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1979,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1979,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,1979,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,1979,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1979,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1979,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,1979,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1979,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1979,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1980,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1980,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1980,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1980,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1980,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1980,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1980,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1980,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1980,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1980,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1981,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1981,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1981,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1981,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1981,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1981,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,1981,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1981,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,1981,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1981,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1981,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1981,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1981,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1982,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1982,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1982,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1982,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1982,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1982,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1982,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,1982,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1982,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1982,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1982,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1983,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1983,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1983,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1983,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1983,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1983,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1983,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1983,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1983,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1983,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1983,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1984,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1984,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1984,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1984,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1984,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1984,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1984,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1984,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1984,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1985,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1985,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1985,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1985,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1985,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,1985,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1985,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1985,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1985,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1985,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1985,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1986,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1986,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1986,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1986,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1986,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1986,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1986,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,1986,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1986,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,1986,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1987,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1987,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1987,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1987,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1987,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1987,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1987,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1987,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1987,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1988,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1988,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1988,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1988,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1988,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1988,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1988,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,1988,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1989,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1989,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1989,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1989,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1989,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1989,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1989,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1989,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1989,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1989,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1990,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1990,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1990,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1990,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1990,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1990,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,1990,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1990,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,1990,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1991,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1991,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1991,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1991,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1991,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1991,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1991,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1991,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1991,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1991,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1991,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1991,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,1991,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1992,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1992,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1992,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1992,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1992,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1992,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1992,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1992,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1992,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1992,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,1992,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1992,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,1992,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1992,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1992,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1992,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1992,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1993,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1993,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1993,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1993,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1993,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1993,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1993,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1993,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1993,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,1993,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1994,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1994,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1994,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1994,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic Movies,1994,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1994,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1994,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1994,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1994,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1994,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1994,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1994,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1994,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1994,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,1994,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1995,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1995,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1995,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1995,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1995,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1995,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1995,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1995,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1995,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1995,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,1995,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1995,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1995,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,1995,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1995,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,1995,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1996,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1996,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1996,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1996,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1996,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1996,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1996,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1996,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1996,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,1996,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1996,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1996,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1996,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1997,14);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1997,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1997,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1997,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1997,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1997,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1997,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1997,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1997,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1997,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1997,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1997,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,1997,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1997,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1997,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1997,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1998,16);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1998,14);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1998,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1998,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1998,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1998,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,1998,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1998,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,1998,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1998,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1998,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1998,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,1998,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1998,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Thrillers,1998,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,1999,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,1999,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,1999,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,1999,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,1999,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,1999,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,1999,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,1999,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,1999,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,1999,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,1999,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,1999,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,1999,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,1999,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2000,16);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2000,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2000,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2000,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2000,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2000,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2000,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2000,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2000,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2000,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2000,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2000,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2000,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2001,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2001,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2001,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2001,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2001,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2001,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2001,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2001,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2001,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2001,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2001,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Mysteries,2001,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2002,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2002,18);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2002,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2002,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2002,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2002,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2002,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2002,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2002,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2002,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2002,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2002,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2002,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2002,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2002,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2002,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2003,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2003,19);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2003,18);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2003,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2003,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2003,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2003,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2003,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2003,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2003,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2003,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2003,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2003,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2003,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2003,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2003,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2003,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2003,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2003,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2003,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2003,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2004,29);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2004,22);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2004,20);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2004,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2004,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2004,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2004,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2004,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2004,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2004,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2004,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2004,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2004,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2004,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2004,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2004,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2004,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2004,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2004,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2005,29);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2005,26);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2005,25);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2005,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2005,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2005,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2005,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2005,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2005,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2005,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2005,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2005,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2005,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2005,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2005,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2005,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2005,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2005,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2005,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2006,41);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2006,36);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2006,35);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2006,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2006,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2006,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2006,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2006,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2006,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2006,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2006,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2006,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2006,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2006,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2006,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2006,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2006,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2006,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2006,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2006,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2006,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2006,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2006,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,2006,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2007,32);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2007,32);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2007,30);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2007,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2007,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2007,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2007,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2007,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2007,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2007,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2007,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2007,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2007,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2007,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2007,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2007,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2007,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2007,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2007,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy & Talk Shows,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Mysteries,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2007,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2008,49);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2008,47);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2008,43);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2008,24);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2008,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2008,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2008,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2008,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2008,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2008,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2008,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2008,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2008,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2008,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2008,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2008,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2008,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2008,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2008,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2008,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2008,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2008,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2008,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2008,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2008,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2008,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2008,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2008,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy & Talk Shows,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Horror,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Thrillers,2008,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2009,50);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2009,42);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2009,41);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2009,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2009,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2009,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2009,16);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2009,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2009,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2009,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2009,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2009,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2009,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2009,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2009,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2009,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2009,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2009,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2009,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2009,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2009,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2009,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2009,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2009,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2009,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2009,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2009,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2009,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2009,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2009,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2009,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2010,75);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2010,66);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2010,52);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2010,29);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2010,27);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2010,22);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2010,18);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2010,14);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2010,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2010,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2010,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2010,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2010,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2010,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2010,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2010,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2010,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2010,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2010,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2010,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2010,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2010,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2010,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2010,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2010,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2010,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2010,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2010,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2010,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2010,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2010,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2010,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2010,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2011,60);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2011,55);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2011,51);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2011,26);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2011,26);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2011,23);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2011,23);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2011,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2011,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2011,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2011,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2011,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2011,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2011,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2011,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2011,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2011,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2011,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2011,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2011,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2011,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2011,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2011,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2011,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2011,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2011,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2011,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2011,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2011,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2011,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2011,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2011,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2011,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Horror,2011,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2012,80);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2012,66);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2012,61);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2012,36);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2012,29);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2012,25);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2012,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2012,20);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2012,19);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2012,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2012,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2012,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2012,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2012,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2012,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2012,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2012,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2012,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2012,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2012,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2012,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2012,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2012,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2012,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2012,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2012,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2012,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2012,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2012,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2012,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2012,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2012,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2012,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2012,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2013,121);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2013,83);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2013,65);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2013,40);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2013,34);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2013,32);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2013,30);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2013,29);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2013,20);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2013,18);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2013,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2013,16);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2013,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2013,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2013,14);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2013,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2013,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2013,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2013,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2013,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2013,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2013,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2013,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2013,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2013,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2013,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2013,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2013,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2013,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2013,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2013,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2013,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2013,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy & Talk Shows,2013,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Mysteries,2013,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2013,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Thrillers,2013,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2014,127);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2014,104);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2014,79);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2014,47);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2014,39);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2014,35);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2014,31);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2014,31);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2014,29);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2014,28);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2014,22);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2014,19);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2014,18);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2014,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2014,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2014,14);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2014,13);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2014,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2014,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2014,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2014,10);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2014,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2014,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2014,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2014,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2014,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2014,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2014,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2014,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2014,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2014,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Horror,2014,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2014,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2014,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy & Talk Shows,2014,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Mysteries,2014,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,2014,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Thrillers,2014,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2015,210);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2015,180);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2015,94);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2015,93);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2015,67);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2015,65);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2015,53);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2015,50);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2015,40);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2015,37);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2015,34);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2015,32);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2015,25);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2015,24);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2015,24);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2015,23);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2015,22);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2015,21);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2015,20);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2015,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2015,16);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2015,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2015,15);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2015,12);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2015,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2015,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2015,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2015,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Horror,2015,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Thrillers,2015,8);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2015,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Mysteries,2015,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2015,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2015,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2015,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2015,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy & Talk Shows,2015,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2015,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2015,2);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Shows,2015,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2016,305);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2016,265);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2016,150);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2016,137);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2016,133);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2016,101);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2016,80);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2016,73);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Thrillers,2016,72);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Comedies,2016,47);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Kids' TV,2016,46);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic TV Shows,2016,46);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Children & Family Movies,2016,45);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Romantic Movies,2016,41);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Crime TV Shows,2016,39);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy,2016,37);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Docuseries,2016,36);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Horror Movies,2016,32);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sports Movies,2016,32);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (British TV Shows,2016,30);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Music & Musicals,2016,27);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Korean TV Shows,2016,26);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Reality TV,2016,24);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Sci-Fi & Fantasy,2016,22);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Spanish-Language TV Shows,2016,17);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Science & Nature TV,2016,16);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Series,2016,11);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (LGBTQ Movies,2016,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Action & Adventure,2016,9);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Mysteries,2016,7);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Movies,2016,6);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Anime Features,2016,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Teen TV Shows,2016,5);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Horror,2016,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Sci-Fi & Fantasy,2016,4);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Faith & Spirituality,2016,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Thrillers,2016,3);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Classic & Cult TV,2016,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Cult Movies,2016,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Stand-Up Comedy & Talk Shows,2016,1);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International Movies,2017,328);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Dramas,2017,285);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Documentaries,2017,172);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Comedies,2017,164);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (International TV Shows,2017,136);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Independent Movies,2017,113);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (Action & Adventure,2017,89);
INSERT INTO `` (`genre`,`release_year`,`total`) VALUES (TV Dramas,2017,77);
